version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db_lojas
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: desafio_lojas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./back
    container_name: go_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: desafio_lojas
    command: ["/app/main"]

  frontend:
    build:
      context: ./front/nuxt-frontend 
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NITRO_PORT: 3000
      API_BASE_URL: "http://backend:8080" 

volumes:
  postgres_data: